apiVersion: v1
kind: Namespace
metadata:
  name: ml-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-deployment
  namespace: ml-dev
  labels:
    app: house-price
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-price
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: house-price
    spec:
      containers:
        - name: house-price
          image: bhavika123/house-price-service:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: house-price-svc
  namespace: ml-dev
spec:
  selector:
    app: house-price
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: house-price-hpa
  namespace: ml-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: house-price-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60